In [2]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, LabelBinarizer, OneHotEncoder
from sklearn.feature_extraction import DictVectorizer, FeatureHasher
np.random.seed(1000)

In [10]:
Y = np.random.choice(('female','male'),size=(10))
print(Y)
print("Label Encoding")
le = LabelEncoder()
yt = le.fit_transform(Y)
print(yt)

['female' 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'female'
 'female']
Label Encoding
[0 0 1 1 0 1 0 1 0 0]


In [11]:
## Decode dummy output
print('Label Decoding')
output = [1, 0, 1, 1, 0, 0]
ty = [le.classes_[i] for i in output]
print(ty)


Label Decoding
['male', 'female', 'male', 'male', 'female', 'female']


In [12]:
## Label Binarization
print('Label Binaraization')
lb = LabelBinarizer()
bt = lb.fit_transform(Y)
print(bt)

Label Binaraization
[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]]


In [13]:
## Decode Binaraization
print("Decode Binaraization")
lb.inverse_transform(bt)

Decode Binaraization


array(['female', 'female', 'male', 'male', 'female', 'male', 'female',
       'male', 'female', 'female'], dtype='<U6')

In [15]:
# Define some dictionary data
data = [
    {'feature_1': 10, 'feature_2': 15},
    {'feature_1': -5, 'feature_3': 22},
    {'feature_3': -2, 'feature_4': 10}
]

In [19]:
print("Dictionary Data Vectoraization")
dv = DictVectorizer()
dt = dv.fit_transform(data)
print(dt.todense())

Dictionary Data Vectoraization
[[10. 15.  0.  0.]
 [-5.  0. 22.  0.]
 [ 0.  0. -2. 10.]]


In [21]:
print('Vocabulary:')
print(dv.vocabulary_)

Vocabulary:
{'feature_1': 0, 'feature_2': 1, 'feature_3': 2, 'feature_4': 3}


In [22]:
print('Feature Hashing')
fh = FeatureHasher()
ft = fh.fit_transform(data)
print(ft)

Feature Hashing
  (0, 43935)	10.0
  (0, 411053)	15.0
  (1, 43935)	-5.0
  (1, 357773)	22.0
  (2, 357773)	-2.0
  (2, 687220)	-10.0


In [27]:
print('decode the features')
print('Feature decoding')
print(ft.todense())

decode the features
Feature decoding
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
# Encode data
# One-hot encoding
data1 = [
    [0, 10],
    [1, 11],
    [1, 8],
    [0, 12],
    [0, 15]
]
oh = OneHotEncoder()
Y_oh = oh.fit_transform(data1)
print(Y_oh.todense())

[[1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1.]]
