In [4]:
import numpy as np
from sklearn.impute import SimpleImputer

In [7]:
data = np.array([[1, np.nan, 2], [2, 3, np.nan], [-1, 4, 2]])
print(data)

[[ 1. nan  2.]
 [ 2.  3. nan]
 [-1.  4.  2.]]


In [9]:
print('Mean strategy')
imp  = SimpleImputer(strategy='mean')
print(imp.fit_transform(data))
print('Median Strategy')
imp  = SimpleImputer(strategy='median')
print(imp.fit_transform(data))
print('Most-frequent strategy')
imp = SimpleImputer(strategy='most_frequent')
print(imp.fit_transform(data))

Mean strategy
[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]
Median Strategy
[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]
Most-frequent strategy
[[ 1.  3.  2.]
 [ 2.  3.  2.]
 [-1.  4.  2.]]
